services:
    nelmio_security.clickjacking_listener:
        scope: request
        class: Nelmio\SecurityBundle\Listener\ClickjackingListener
        arguments:
            - %nelmio_security.clickjacking.paths%
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
