services:
    nelmio_security.signed_cookie_listener:
        scope: request
        class: Nelmio\SecurityBundle\SignedCookieListener
        arguments:
            - @nelmio_security.signer
            - %nelmio_security.signed_cookie.names%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 300 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    nelmio_security.signer:
        class: Nelmio\SecurityBundle\Signer
        arguments:
            - %nelmio_security.signer.secret%
