language: php

cache:
  directories:
    - .phpunit

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;

install:
  - if [[ $TRAVIS_PHP_VERSION != '5.5' ]]; then composer install ; fi
  - if [[ $TRAVIS_PHP_VERSION == '5.5' ]]; then composer update --prefer-lowest ; fi

script:
  - export SYMFONY_PHPUNIT_DIR=`pwd`/.phpunit
  - ./vendor/bin/simple-phpunit

matrix:
  include:
    - php: 7.1

